# netlify.toml (Final, Most Robust Version)

[build]
  # Tell Netlify that the frontend code is in the 'client' subdirectory
  base = "client" 
  
  # --- THE DEFINITIVE FIX ---
  # 1. `npm ci`: Does a clean install of all dependencies from package-lock.json.
  # 2. `npx vite build`: Explicitly tells the system to find and run the `vite`
  #    executable from the local `node_modules` folder.
  command = "npm ci && npx vite build"
  
  # The output folder created by `vite build`
  publish = "dist"

[build.secrets]
  # This list remains the same.
  omit = [
    "VITE_CLOUDINARY_CLOUD_NAME",
    "VITE_CLOUDINARY_API_KEY",
    "VITE_SOCKET_URL",
    "VITE_API_URL",
    "VITE_GOOGLE_CLIENT_ID",
    "VITE_STRIPE_PUBLISHABLE_KEY"
  ]