# netlify.toml

[build]
  # This path should be correct, pointing to your frontend folder
  base = "client" 
  
  # --- THIS IS THE FIX ---
  # Chain the install command with the build command.
  # "npm install" will run first, then "npm run build" will run.
  command = "npm install && npm run build"
  
  # The publish directory is where the build output is placed.
  publish = "dist"

[build.secrets]
  # This list of keys to omit is still correct.
  omit = [
    "VITE_CLOUDINARY_CLOUD_NAME",
    "VITE_CLOUDINARY_API_KEY",
    "VITE_SOCKET_URL",
    "VITE_API_URL",
    "VITE_GOOGLE_CLIENT_ID",
    "VITE_STRIPE_PUBLISHABLE_KEY"
  ]